content:
  - name: notes
    label: Notes
    path: app/content/notes
    type: collection
    subfolders: false
    format: yaml-frontmatter
    filename: '{primary}.md'
    fields:
      - name: title
        label: Title
        type: string
      - name: link
        label: Link
        type: string
      - name: date
        label: Date
        type: date
        options:
          format: yyyy-MM-dd HH:mm:ssXX
          time: true
      - name: body
        label: Body
        type: text
    view:
      fields: [ title, date ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: date
        order: desc