[[headers]]
	for = "/*"

	[headers.values]
		X-Content-Type-Options = "nosniff"
		Content-Security-Policy = "frame-ancestors 'none';"
		X-Frame-Options = "DENY"
		X-XSS-Protection = "1; mode=block"
		Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
	for = "/rss.xml"
	[headers.values]
		Content-Type = "text/xml"

[[headers]]
	for = "/sitemap.xml"
	[headers.values]
		Content-Type = "text/xml"
