[build]
	publish = "html/"
	command = "npm run prod"

[[headers]]
	for = "/*"

	[headers.values]
		X-Content-Type-Options = "nosniff"
		Content-Security-Policy = "frame-ancestors 'none';"
		X-Frame-Options = "DENY"
		X-XSS-Protection = "1; mode=block"


[[redirects]]
	from = "/notes"
	to = "/category/notes/"
	status = 301

[[redirects]]
	from = "/search"
	to = "https://www.google.com/search?q=site:mikestreety.co.uk"
	status = 301

[[redirects]]
	from = "/blog/p2"
	to = "/blog/1/"
	status = 301
