backend:
  name: github
  repo: mikestreety/mikestreety
  branch: main
media_folder: "public/assets/images"
public_folder: "/assets/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "app/content/blog"
    create: true
    path: "{{year}}/{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "date", format: 'YYYY-MM-DD' }
      - { label: "intro", name: "intro", widget: "string" }
      - { label: "canonical", name: "canonical", widget: "string", required: false }
      - { label: "who", name: "publication", widget: "string", required: false }
      - { label: "tags", name: "tags", widget: "list" }
      - { label: "body", name: "body", widget: "markdown" }
  - name: "notes"
    label: "Notes"
    folder: "app/content/notes"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "datetime", format: 'YYYY-MM-DDTHH:mm:ssZ[Z]' }
      - { label: "link", name: "link", widget: "string" }
      - { label: "body", name: "body", widget: "markdown" }
